import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Navbar from "@/components/shared/Navbar";
import Marquee from "@/components/shared/Marquee";
import Footer from "@/components/shared/Footer";
import { Toaster } from "react-hot-toast";



const notoSerifBengali=Noto_Serif_Bengali({
  subsets:["latin","bengali"]

})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
       data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased bg-[#F3FBF4]`}
    >
      <body className="min-h-full flex flex-col">
        <Header></Header>
        <Navbar></Navbar>
        <Marquee></Marquee>
         <main className="w-full flex-1">
          {children}
        </main>
        <Toaster position="top-right"/>
        <Footer></Footer>
        </body>
    </html>
  );
}
